image: node:latest

stages: # Les étapes associées au projet.
  - test # Test de l'application
  - deploy # Deploiement

before_script:
  - npm i

test-jest:
  services:
    - postgres:14
  variables:
    POSTGRES_USER: $POSTGRES_USER
    POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    POSTGRES_DB: $POSTGRES_DB
    POSTGRES_HOST_AUTH_METHOD: trust
  stage: test
  script:
    - cd server/src/services/
    - npm run db:push
    - npm run db:generate
    - cd ../
    - npx jest
  artifacts:
    paths:
      - server/src/tests/coverage/
badges:
  stage: deploy
  needs: [test-jest] # Les badges dépendent de la vérification de la qualité du code
  script:
    - server/src/tests/badges.sh # Génère les badges de qualité de code
    - npx jest-coverage-badges
  when: always # On veut toujours générer les badges
  artifacts:
    paths:
      - server/src/tests/coverage/
      - server/src/tests/*.svg
