version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres-client
    hostname: postgres
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=ibrahim
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=TMDB
      - DATABASE_URL=postgresql://ibrahim:password@localhost:5432/TMDB?schema=public&sslmode=prefer

    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-q",
          "-h",
          "localhost",
          "-U",
          "postgres"
        ]
      interval: 5s
      timeout: 3s
      retries: 5

  express-server:
    build:
      context: ./server
      args:
        - POSTGRES_USER=ibrahim
        - POSTGRES_PASSWORD=password
        - POSTGRES_DB=TMDB
        - DATABASE_URL=postgresql://ibrahim:password@localhost:5432/TMDB?schema=public&sslmode=prefer
    ports:
      - "3001:3001"
    environment:
      - POSTGRES_USER=ibrahim
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=TMDB
      - DATABASE_URL=postgresql://ibrahim:password@localhost:5432/TMDB?schema=public&sslmode=prefer
    depends_on:
      postgres:
        condition: service_healthy

  react-app:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - express-server
