version: "3.9"
services:
  postgress:
    image: postgres:latest
    environment:
      POSTGRES_DB: TMDB
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  express-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - postgress
    environment:
      - DATABASE_URL=postgresql://ibrahim:password@localhost:5432/TMDB?schema=public&sslmode=prefer

  react-app:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - express-app
