version: "3.9"
services:
  postgres-client:
    image: postgres:latest
    container_name: postgres-client
    hostname: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  express-server:
    build: ./server
    ports:
      - "3001:3001"
    depends_on:
      - postgres-client

  react-app:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - express-server
