version: "3.9"
services:
  postgress:
    image: postgres:latest
    environment:
      POSTGRES_DB: TMDB
      POSTGRES_USER: ibrahim
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  prisma:
    build:
      context: ./app/server/src/services
      dockerfile: Dockerfile
      target: prisma-builder
    depends_on:
      - postgres

  express-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - prisma

  react-app:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - express-app
