###
GET http://localhost:3001/clerk/applications HTTP/1.1
###
GET http://localhost:3001/proposals/title/propOSTA HTTP/1.1
###
GET http://localhost:3001/proposals/teacher/auth0|655fd0b96d87729b6b3e0795 HTTP/1.1
###
GET http://localhost:3001/proposals/cosupervisor/1 HTTP/1.1
###
GET http://localhost:3001/proposals/supervisor/rossi%20mario HTTP/1.1
###
GET http://localhost:3001/proposals/cosupervisor/giulia HTTP/1.1
###
GET http://localhost:3001/proposals/keywords/ARCHITETTURA,crittografia HTTP/1.1
###
GET http://localhost:3001/proposals/groups/Gruppo,gruppo1 HTTP/1.1
###
GET http://localhost:3001/proposals/level/MAGISTRALE HTTP/1.1
###
GET http://localhost:3001/proposals/expiration/2023-11-30 HTTP/1.1
###

GET http://localhost:3001/proposals/cds/CDS1 HTTP/1.1
###

GET http://localhost:3001/proposals/types HTTP/1.1

###
POST http://localhost:3001/ HTTP/1.1

###
GET http://localhost:3001/applications/1 HTTP/1.1

###
GET http://localhost:3001/1 HTTP/1.1
