name: CI/CD

on: push

jobs:
  test-jest:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host:5432/${POSTGRES_DB}
          POSTGRES_HOST_AUTH_METHOD: trust

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16.13

      - name: Install dependencies
        run: |
          cd server/
          npm i

      - name: Prepare PostgreSQL
        run: |
          cd server/src/services/
          npm run db:push
          npm run db:generate
          cd ../
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
          DATABASE_URL: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@host:5432/${POSTGRES_DB}
          POSTGRES_HOST_AUTH_METHOD: trust

      - name: Run Jest tests
        run: |
          npx jest
          npx jest-coverage-badges
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: coverage-artifacts
          path: |
            servers/src/tests/coverage/

  badges:
    runs-on: ubuntu-latest

    needs: test-jest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "latest"

      - name: Install dependencies
        run: |
          cd server/
          npm i

      - name: Generate code quality badges
        run: server/src/tests/badges.sh

      - name: Generate coverage badges
        run: npx jest-coverage-badges

      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: coverage-artifacts

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: badges
          path: |
            servers/src/tests/coverage/*.svg
            servers/src/tests/*.svg
