name: Pull Request Workflow

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for *.test.js files changes
        run: |
          if git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '\.test\.js'; then
            echo "Changes to *.test.js files detected. Proceeding with the push."
          else
            echo "No changes to *.test.js files detected. Skipping the push."
            exit 0  # Exit successfully without further steps
          fi

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Set up Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Run tests
        run: |
          git config user.name ${{github.actor}}
          git config user.email ${{github.actor}}@users.noreply.github.com

          cd server/
          ./update_coverage.sh
          cat README.md
          git status
          git add README.md
          git commit -m "Updating coverage badge"
          git push origin HEAD:refs/heads/${GITHUB_REF#refs/heads/}
